Add support for Open VSX ratings
badgen/badgen.net pull request #512
Opened 2021-02-21 16:33 UTC by idleberg

I somehow missed the ratings option in the Open VSX API. But now that there are two topics with the letter `r`, I'm having second thoughts about the abbreviated forms. Any opinions on whether I should remove that or do you fear a breaking change like this? I'm wondering why there's no recommendation or at least a standardized way for some of these (e.g. I've seen `d` and `dl` as short forms for `downloads`). Personally, when in doubt, I'd opt for the full name topics.

2021-03-11 08:44 UTC, amio commented
> Personally, when in doubt, I'd opt for the full name topics.

Agreed. We are using `v` and `d` or `dl` for historical reasons, let's advocate full name in all other cases 👍

2021-03-12 07:52 UTC, vladimyr commented on api/open-vsx.ts
>      case 'version':
```suggestion
	case 'v':
    case 'version':
```

2021-03-12 08:01 UTC, vladimyr requested changes
> Agreed. We are using `v` and `d` or `dl` for historical reasons, let's advocate full name in all other cases :+1:

@idleberg I might be interpreting this incorrectly but I believe @amio just established a policy that says the following:
- **version** route should support both short (`v`) and long forms
- **license** route should support both short (`l`) and long forms _(my own addition to follow the suit based upon historical precedence)_
- **download count** routes should use short forms exclusively (`d` for downloads, `dt` for total downloads, `dm` for monthly downloads, and so on)
- every **other** route should use a long (kebab-case) form exclusively

According to that, I propose the following changes...

2021-03-12 08:40 UTC, vladimyr requested changes
Sorry, I missed the route pattern in the previous review.
Also, the download count route should become `/d` instead of `/downloads` ie supporting only short form.

> * **download count** routes should use short forms exclusively (`d` for downloads, `dt` for total downloads, `dm` for monthly downloads, and so on)

2021-03-12 08:42 UTC, vladimyr commented on api/open-vsx.ts
> +    '/open-vsx/:topic<downloads|license|rating|reviews|version>/:namespace/:pkg': handler
```suggestion
    '/open-vsx/:topic<d|l|license|rating|reviews|v|version>/:namespace/:pkg': handler
```

2021-03-12 09:13 UTC, vladimyr commented
@idleberg I feel I'm really messing up with your time :cry: 

So this time I offer you something better:

```patch
diff --git a/api/open-vsx.ts b/api/open-vsx.ts
index bf2a1b7..457dfb4 100644
--- a/api/open-vsx.ts
+++ b/api/open-vsx.ts
@@ -6,7 +6,7 @@ import { createBadgenHandler, PathArgs } from '../libs/create-badgen-handler'
 export default createBadgenHandler({
   title: 'Open VSX',
   examples: {
-    '/open-vsx/downloads/idleberg/electron-builder': 'downloads',
+    '/open-vsx/d/idleberg/electron-builder': 'downloads',
     '/open-vsx/license/idleberg/electron-builder': 'license',
     '/open-vsx/rating/idleberg/electron-builder': 'rating',
     '/open-vsx/reviews/idleberg/electron-builder': 'reviews',
@@ -30,7 +30,6 @@ async function handler ({ topic, pkg, namespace }: PathArgs) {
         color: versionColor(data.version)
       }
     case 'd':
-    case 'downloads':
       return {
         subject: 'downloads',
         status: millify(data.downloadCount),
@@ -55,11 +54,5 @@ async function handler ({ topic, pkg, namespace }: PathArgs) {
         status: millify(data.reviewCount),
         color: 'green'
       }
-    default:
-      return {
-        subject: 'Open VSX',
-        status: 'unknown',
-        color: 'grey'
-      }
   }
 }

```
Patch download: http://sprunge.us/btxqXj

The default case is redundant if you explicitly match all possible routes using a route pattern. :point_up:

2021-03-16 19:08 UTC, vladimyr approved these changes

2021-03-17 08:49 UTC, amio commented
Thanks! @idleberg @vladimyr

2021-03-23 09:01 UTC, merged